export default {
  projects: [
    {
      id: "lanuitlumiere",
      title: "La Nuit Lumière",
      subtitle: "La Nuit Blanche Taipei 2022",
      cover: "projects/laNuit-Cover.jpg",
      innerCover: "projects/laNuit-CoverInner.jpg",
      descrpition: `La nuit lumiere is generated by the data of participants accumulated throughout the 12 hours of Nuit Blanche Taipei 2022. The participant flow and the audience credit mission trigger the ratio of RGB color values, which represents “avant grade,” “guarding” and “balance.” 

Everyone’s authentic experience is fantastically transformed into real-time data of the virtual world, which is converged and converted into the lumiere of the night, shining for the belief of all and merging with the sun at 6 am.
    
At the moment of sunrise, step towards the future.
      
6pm-6am. Once every hour, 12 times in total.`,
      medias: [
        {
          type: "image",
          url: "projects/laNuit-01.jpg",
        },
        {
          type: "image",
          url: "projects/laNuit-02.jpg",
        },
        {
          type: "image",
          url: "projects/laNuit-03.jpg",
        },
        {
          type: "vimeo",
          url: "https://vimeo.com/764434760/978e00b006",
        },
      ],
    },
    {
      id: "datafaceprint",
      title: "Data Face Print",
      subtitle: "Barbican Centre - AI: More Than Human",
      cover: "projects/dfp-Cover.jpg",
      innerCover: "projects/dfp-CoverInner.jpg",
      descrpition: "Data Face Print",
      medias: [
        {
          type: "image",
          url: "projects/dfp01.jpg",
        },
        {
          type: "image",
          url: "projects/dfp02.jpg",
        },
        {
          type: "vimeo",
          url: "https://vimeo.com/387633341",
        },
        {
          type: "image",
          url: "projects/dfp03.jpg",
        },
      ],
    },
    {
      id: "pulse",
      title: "FC Bayern - Pulse",
      subtitle: "Visualisation of a football game",
      cover: "projects/pulseCover.jpg",
      innerCover: "projects/pulseCoverInner.jpg",
      descrpition: "Visualisation of a football game",
      medias: [
        {
          type: "image",
          url: "projects/pulse03.jpg",
        },
        {
          type: "image",
          url: "projects/pulse02.jpg",
        },
        {
          type: "image",
          url: "projects/pulse01.jpg",
        },
      ],
    },
    {
      id: "sibos",
      title: "Sibos",
      subtitle: "2018",
      cover: "projects/sibosCover.jpg",
      innerCover: "projects/sibosCoverInner.jpg",
      descrpition: "Visualisation of a football game",
      medias: [
        {
          type: "vimeo",
          url: "https://vimeo.com/534333355",
        },
        {
          type: "image",
          url: "projects/sibos00.jpg",
        },
        {
          type: "image",
          url: "projects/sibos01.jpg",
        },
        {
          type: "image",
          url: "projects/sibos02.jpg",
        },
        {
          type: "image",
          url: "projects/sibos03.jpg",
        },

        {
          type: "vimeo",
          url: "https://vimeo.com/534357972",
        },
      ],
    },
  ],
  generatives: {
    fireWithin: {
      title: "The Fire Within",
      path: "fireWithin.jpg",
      url: "https://www.fxhash.xyz/generative/20140",
      editions: 256,
    },
    collage: {
      title: "Collage",
      path: "collage.jpg",
      url: "https://www.fxhash.xyz/generative/11805",
      editions: 333,
    },
    sketching: {
      title: "Sketching",
      path: "sketching.jpg",
      url: "https://www.fxhash.xyz/generative/8084",
      editions: 512,
    },
    wondering: {
      title: "Wondering",
      path: "wondering.jpg",
      url: "https://www.fxhash.xyz/generative/4680",
      editions: 256,
    },
    percentage: {
      title: "Project%",
      path: "percentage.jpg",
      url: "https://project.fab.tw/",
    },
    strand: {
      title: "Strand",
      path: "strand.jpg",
      url: "https://www.fxhash.xyz/generative/3266",
      editions: 256,
    },
    labyrinth: {
      title: "Labyrinth",
      path: "labyrinth.jpg",
      url: "https://www.fxhash.xyz/generative/2501",
      editions: 256,
    },
    maze: {
      title: "Maze",
      path: "maze.jpg",
      url: "https://www.fxhash.xyz/generative/1870",
      editions: 128,
    },
    hex: {
      title: "Hex",
      path: "hex.jpg",
      url: "https://www.fxhash.xyz/generative/1762",
      editions: 128,
    },
    rubixCube: {
      title: "Rubik's Cube",
      path: "rubixCube.jpg",
      url: "https://www.fxhash.xyz/generative/1983",
      editions: 256,
    },
    excursion: {
      title: "Excursion",
      path: "excursion.jpg",
      url: "https://www.fxhash.xyz/generative/1205",
      editions: 128,
    },
    threads: {
      title: "Threads",
      path: "threads.jpg",
      url: "https://www.fxhash.xyz/generative/671",
      editions: 512,
    },
    circles: {
      title: "Circles",
      path: "circles.jpg",
      url: "https://www.fxhash.xyz/generative/316",
      editions: 512,
    },
  },
};
